# hadolint ignore=DL3006,DL3007 
#FROM eafxx/alpine-python
FROM ghcr.io/linuxserver/baseimage-alpine:3.13
LABEL MAINTAINER="Tr4il - original by eafxx"

ENV \
  APP_DIR=traktarr \
  TRAKTARR_CONFIG=/config/config.json \
  TRAKTARR_LOGFILE=/config/traktarr.log \
  TZ="Europe/Berlin"

RUN \
  echo "**** install packages ****" && \
  apk add  -U --update --no-cache \
    curl \
    git \
    python3 \
    py3-pip \
    py3-setuptools \
    tzdata

# add local files
COPY root/ /

# Install packages
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
# hadolint ignore=DL3018,DL3003,DL3013
RUN \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    pip3 install --no-cache-dir --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    bash /etc/cont-init.d/30-install

# Change directory
WORKDIR /${APP_DIR}

# Config volume
VOLUME /config